/**
 * Generated by API Builder - https://www.apibuilder.io
 * Service version: 1.0.1
 * apibuilder app.apibuilder.io/nashtech/order/latest/play_2_6_controllers
 */
package com.nashtech.order.v1.controllers

import com.nashtech.order.v1.models.json._

trait OrdersController extends play.api.mvc.BaseController {

  sealed trait GetByNumber extends Product with Serializable
  object GetByNumber {
    final case class HTTP200(body: com.nashtech.order.v1.models.Order) extends GetByNumber
    case object HTTP401 extends GetByNumber
    case object HTTP404 extends GetByNumber
    final case class Undocumented(result: play.api.mvc.Result) extends GetByNumber
  }

  def getByNumber(
                   request: play.api.mvc.Request[play.api.mvc.AnyContent],
                   merchantId: String,
                   number: String
                 ): scala.concurrent.Future[GetByNumber]
  final def getByNumber(merchantId: String, number: String): play.api.mvc.Action[play.api.mvc.AnyContent] =
    Action.async { request =>
      getByNumber(request, merchantId, number)
        .map {
          case r: GetByNumber.HTTP200      => Status(200)(play.api.libs.json.Json.toJson(r.body))
          case GetByNumber.HTTP401         => Status(401)(play.api.mvc.Results.EmptyContent())
          case GetByNumber.HTTP404         => Status(404)(play.api.mvc.Results.EmptyContent())
          case r: GetByNumber.Undocumented => r.result
        }(defaultExecutionContext)
    }

  sealed trait GetAll extends Product with Serializable
  object GetAll {
    final case class HTTP200(body: Seq[com.nashtech.order.v1.models.Order]) extends GetAll
    case object HTTP401 extends GetAll
    case object HTTP404 extends GetAll
    final case class Undocumented(result: play.api.mvc.Result) extends GetAll
  }

  def getAll(
              request: play.api.mvc.Request[play.api.mvc.AnyContent],
              merchantId: String
            ): scala.concurrent.Future[GetAll]
  final def getAll(merchantId: String): play.api.mvc.Action[play.api.mvc.AnyContent] = Action.async { request =>
    getAll(request, merchantId)
      .map {
        case r: GetAll.HTTP200      => Status(200)(play.api.libs.json.Json.toJson(r.body))
        case GetAll.HTTP401         => Status(401)(play.api.mvc.Results.EmptyContent())
        case GetAll.HTTP404         => Status(404)(play.api.mvc.Results.EmptyContent())
        case r: GetAll.Undocumented => r.result
      }(defaultExecutionContext)
  }

  sealed trait Post extends Product with Serializable
  object Post {
    final case class HTTP200(body: com.nashtech.order.v1.models.Order) extends Post
    case object HTTP401 extends Post
    case object HTTP404 extends Post
    final case class HTTP422(body: com.nashtech.order.v1.models.Error) extends Post
    final case class Undocumented(result: play.api.mvc.Result) extends Post
  }

  def post(
            request: play.api.mvc.Request[com.nashtech.order.v1.models.OrderForm],
            merchantId: String,
            body: com.nashtech.order.v1.models.OrderForm
          ): scala.concurrent.Future[Post]
  final def post(merchantId: String): play.api.mvc.Action[com.nashtech.order.v1.models.OrderForm] =
    Action.async(parse.json[com.nashtech.order.v1.models.OrderForm]) { request =>
      post(request, merchantId, request.body)
        .map {
          case r: Post.HTTP200      => Status(200)(play.api.libs.json.Json.toJson(r.body))
          case Post.HTTP401         => Status(401)(play.api.mvc.Results.EmptyContent())
          case Post.HTTP404         => Status(404)(play.api.mvc.Results.EmptyContent())
          case r: Post.HTTP422      => Status(422)(play.api.libs.json.Json.toJson(r.body))
          case r: Post.Undocumented => r.result
        }(defaultExecutionContext)
    }

  sealed trait Put extends Product with Serializable
  object Put {
    final case class HTTP200(body: com.nashtech.order.v1.models.Order) extends Put
    case object HTTP401 extends Put
    case object HTTP404 extends Put
    final case class HTTP422(body: com.nashtech.order.v1.models.Error) extends Put
    final case class Undocumented(result: play.api.mvc.Result) extends Put
  }

  def put(
           request: play.api.mvc.Request[com.nashtech.order.v1.models.OrderForm],
           merchantId: String,
           body: com.nashtech.order.v1.models.OrderForm
         ): scala.concurrent.Future[Put]
  final def put(merchantId: String): play.api.mvc.Action[com.nashtech.order.v1.models.OrderForm] =
    Action.async(parse.json[com.nashtech.order.v1.models.OrderForm]) { request =>
      put(request, merchantId, request.body)
        .map {
          case r: Put.HTTP200      => Status(200)(play.api.libs.json.Json.toJson(r.body))
          case Put.HTTP401         => Status(401)(play.api.mvc.Results.EmptyContent())
          case Put.HTTP404         => Status(404)(play.api.mvc.Results.EmptyContent())
          case r: Put.HTTP422      => Status(422)(play.api.libs.json.Json.toJson(r.body))
          case r: Put.Undocumented => r.result
        }(defaultExecutionContext)
    }

  sealed trait Delete extends Product with Serializable
  object Delete {
    case object HTTP200 extends Delete
    case object HTTP401 extends Delete
    case object HTTP404 extends Delete
    final case class HTTP422(body: com.nashtech.order.v1.models.Error) extends Delete
    final case class Undocumented(result: play.api.mvc.Result) extends Delete
  }

  def delete(
              request: play.api.mvc.Request[play.api.mvc.AnyContent],
              merchantId: String
            ): scala.concurrent.Future[Delete]
  final def delete(merchantId: String): play.api.mvc.Action[play.api.mvc.AnyContent] = Action.async { request =>
    delete(request, merchantId)
      .map {
        case Delete.HTTP200         => Status(200)(play.api.mvc.Results.EmptyContent())
        case Delete.HTTP401         => Status(401)(play.api.mvc.Results.EmptyContent())
        case Delete.HTTP404         => Status(404)(play.api.mvc.Results.EmptyContent())
        case r: Delete.HTTP422      => Status(422)(play.api.libs.json.Json.toJson(r.body))
        case r: Delete.Undocumented => r.result
      }(defaultExecutionContext)
  }

}
